name: NotEnoughItems
version: '${project.version}'
main: io.github.Main
api-version: 1.16
depends: [PlaceholderAPI]
commands:
  spacehelm:
    permission: skyblock.spacehelm
    permission-message: You don't have access to this command!
  $aib:
    permission: skyblock.admin
    permission-message: You don't have access to this command!